seed: 0
gridverse_env: gv_empty.8x8.yaml
include_dashboard: false

defaults:
  - algorithm: ppo
  - environment: gridverse
  - hyperparameters: ppo
  - evaluation: default
  - logging: default
  - resources: default
  - tuner: default
  - _self_

hydra:
  run:
    dir: ./runs/experiments-${now:%Y-%m-%d}/experiment-${now:%H-%M-%S}
