evaluation_interval: 0
evaluation_duration: 2
evaluation_duration_unit: "episodes"
evaluation_parallel_to_training: false
evaluation_force_reset_envs_before_iteration: true
evaluation_config:
  max_rollout_len: 30
evaluation_num_env_runners: 0

video_fps: 4
