training:
  discount_factor: 0.5
  learning_rate: 1e-2
  max_episode_steps: 30

  total_num_steps: 1e5
  batch_size: 128

  num_env_steps_for_each_gradient_update: 256
  num_epochs_optimizing_surrogate_loss: 10
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null
  
testing:
  max_episode_steps: 25
  n_eval_episodes: 100