training:
  learning_rate: 1e-3
  gamma: 0.6

  max_rollout_len: 30
  train_batch_size_per_learner: 256
  num_train_loop: 10

  num_epochs: 10
  minibatch_size: 128
  shuffle_batch_per_epoch: false

  grad_clip: 0.5
  grad_clip_by: 'norm'

  use_critic: true
  use_gae: true
  lambda_: 0.95

  use_kl_loss: false
  kl_coeff: 0.1
  kl_target: null

  vf_loss_coeff: 0.5
  entropy_coeff: 0.000

  clip_param: 0.2
  vf_clip_param: null


testing:
  max_episode_steps: 30
  n_eval_episodes: 100