checkpoint_frequency: 0
checkpoint_at_end: true
num_to_keep: 3

num_samples: 4
max_concurrent_trials: 4
num_cpu_per_trial: 2 # there's 10 cpus/cores/processors in my macbook
max_time_limit_per_trial_seconds: 300
global_time_budget: 1200

population_based_training:
  time_attr: "training_iteration"
  perturbation_interval: 20
  resample_probability: 0.25