checkpoint_frequency: 0
checkpoint_at_end: false
num_to_keep: 1 # num_checkpoints_to_keep

num_samples: 10
max_concurrent_trials: 6
num_cpu_per_trial: 1 # there's 10 cpus/cores/processors in my macbook
max_time_limit_per_trial_seconds: 300
global_time_budget: 1800

population_based_training:
  time_attr: "training_iteration"
  perturbation_interval: 20
  resample_probability: 0.5