seed: 0
gridverse_env: gv_memory.5x5.yaml
use_gpu: false

hydra:
  sweeper:
    params:
      hyperparameters.training.learning_rate: 1e-3, 1e-5
      hyperparameters.training.discount_factor: 0.5, 0.8, 0.99
      hyperparameters.training.max_episode_steps: 20, 30, 40
      hyperparameters.training.batch_size: 64, 128, 256

defaults:
  - algorithm: ppo
  - environment: gridverse
  - hyperparameters: ppo
  - logging: default
  - _self_
  - override hydra/launcher: joblib