seed: 0

policy_net:
  hidden_layers: [ 64, 64 ]

replay_buffer_memory: 1e4

grid_feature_extraction:
  embedding_dim: 8
  cnn_output_dim: 64

training:
  num_steps: 1000
  batch_size: 128
  discount_factor: 0.8
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.1
  learning_rate: 1e-3
  target_update_interval: 100
  learning_starts: 100
  log_interval: 100