seed: 0
use_cuda: true

episode_length: 200
num_episodes: 3
log_interval: 10

learning_rate: 1e4
replay_buffer_memory: 1e4
batch_size: 32

policy_epsilon: 1e-1
discount_factor: 0.99

policy_net:
  hidden_layers: [ 128, 128 ]