seed: 0

policy_net:
  hidden_layers: [ 64, 64 ]

replay_buffer_memory: 1e4

grid_feature_extraction:
  embedding_dim: 8
  cnn_output_dim: 64

training:
  num_steps: 10_00
  max_episode_steps: 100
  batch_size: 128
  discount_factor: 0.7
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.1
  learning_rate: 1e-3
  target_update_interval: 100
  learning_starts: 100
  log_episode_interval: 100
  train_freq: 1
  gradient_steps: 2
  video:
    record_step_interval: 100
    length: 100
    fps: 4

testing:
  max_episode_steps: 100
  n_eval_episodes: 10
  video:
    record_step_interval: 10
    length: 100
    fps: 4