encoder:
  grid_encoder:
    embedding_dim: 16
    type: cnn
    output_dim: 32
    conv_layers:
      - in_channels: ${...embedding_dim}
        out_channels: 32
        kernel_size: 5
        stride: 1
        padding: 1
  agent_id_encoder:
    type: cnn
    output_dim: 16
    conv_layers:
      - in_channels: 1
        out_channels: 16
        kernel_size: 3
        stride: 1
        padding: 0
  items_encoder:
    embedding_dim: 16
    layers: [ 32 ]

#ray/rllib/core/rl_module/default_model_config.py
# Head config
head_fcnet_hiddens: [ 128, 64, 32 ]
head_fcnet_activation: 'relu'
head_fcnet_kernel_initializer: 'xavier_uniform_'
head_fcnet_bias_initializer: 'zeros_'

# Cont. actions
vf_share_layers: true

# Lstm config
use_lstm: true
max_seq_len: 2
lstm_cell_size: 128
lstm_kernel_initializer: 'xavier_uniform_'
lstm_bias_initializer: 'zeros_'